# Upptime Configuration - PYME Instance
# https://upptime.js.org/docs/configuration

owner: agonzaji
repo: status-pyme

sites:
  - name: Platform
    url: https://osp-pyme.messaging-platform.com/health
    icon: https://osp-pyme.messaging-platform.com/images/logo-icon.png
    expectedStatusCodes:
      - 200

  - name: API
    url: https://osp-pyme.messaging-platform.com/api/benchmark/health
    expectedStatusCodes:
      - 200

status-website:
  # cname: status.osp-pyme.messaging-platform.com  # TODO: Enable when domain transfer completes
  logoUrl: https://osp-pyme.messaging-platform.com/images/logo.png
  name: MasOrange PYME Status
  introTitle: "Platform Status"
  introMessage: "Real-time status of MasOrange PYME services."
  navbar:
    - title: Platform
      href: https://osp-pyme.messaging-platform.com
    - title: Support
      href: https://osp-pyme.messaging-platform.com/tickets.html

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  uptime: "*/5 * * * *"

commitMessages:
  commitAuthorName: "Upptime Bot"
  commitAuthorEmail: "upptime@masorange.es"

i18n:
  activeIncidents: "Active Incidents"
  allSystemsOperational: "All Systems Operational"
  incidentReport: "Incident Report"
  pastIncidents: "Past Incidents"
  scheduledMaintenance: "Scheduled Maintenance"
  responseTime: "Response Time"
  uptime: "Uptime"
